"""Second pass enrichment for schools with alternate naming conventions."""
import asyncio, os

with open(os.path.join(os.path.dirname(__file__), '..', '.env')) as f:
    for line in f:
        line = line.strip()
        if '=' in line and not line.startswith('#'):
            k, v = line.split('=', 1)
            os.environ[k] = v.strip('"').strip("'")

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from database import db

# Alternate name → mascot mapping for remaining 350 schools
ALT_MASCOTS = {
    "California Polytechnic State University – San Luis Obispo": "Mustangs",
    "California State University – Bakersfield": "Roadrunners",
    "California State University – Fresno": "Bulldogs",
    "California State University – Fullerton": "Titans",
    "California State University – Long Beach": "Beach",
    "California State University – Northridge": "Matadors",
    "California State University – Sacramento": "Hornets",
    "Canisius University": "Golden Griffins",
    "College of the Holy Cross": "Crusaders",
    "Utah Tech University (formerly Dixie State)": "Trailblazers",
    "Georgia Tech": "Yellow Jackets",
    "Grambling State University": "Tigers",
    "Houston Christian University": "Huskies",
    "Indiana University-Purdue University – Indianapolis (IUPUI)": "Jaguars",
    "Louisiana State University (LSU)": "Tigers",
    "Manhattan University": "Jaspers",
    "New Jersey Institute of Technology": "Highlanders",
    "Northwestern State University of Louisiana": "Demons",
    "Prairie View A & M University": "Panthers",
    "Purdue University – Fort Wayne": "Mastodons",
    "Robert Morris University – Pennsylvania": "Colonials",
    "Saint Mary's College of California": "Gaels",
    "Southern Methodist University – SMU": "Mustangs",
    "Southern University & A&M College": "Jaguars",
    "St. John's University – New York": "Red Storm",
    "Stephen F Austin State University": "Ladyjacks",
    "SUNY Binghamton University": "Bearcats",
    "SUNY Stony Brook University": "Seawolves",
    "SUNY University at Albany": "Great Danes",
    "SUNY University at Buffalo": "Bulls",
    "Texas A&M University – Corpus Christi": "Islanders",
    "Texas A&M University – Commerce": "Lions",
    "Texas A&M University – Kingsville": "Javelinas",
    "University of Alabama – Birmingham (UAB)": "Blazers",
    "University of Alabama in Huntsville (UAH)": "Chargers",
    "University of Alaska – Anchorage": "Seawolves",
    "University of Alaska – Fairbanks": "Nanooks",
    "University of Arkansas – Little Rock": "Trojans",
    "University of Arkansas – Pine Bluff": "Golden Lions",
    "University of California – Davis": "Aggies",
    "University of California – Irvine": "Anteaters",
    "University of California – Los Angeles (UCLA)": "Bruins",
    "University of California – Riverside": "Highlanders",
    "University of California – San Diego": "Tritons",
    "University of California – Santa Barbara": "Gauchos",
    "University of California – Santa Cruz": "Banana Slugs",
    "University of California – Berkeley": "Golden Bears",
    "University of Central Missouri": "Jennies",
    "University of Colorado – Boulder": "Buffaloes",
    "University of Colorado – Colorado Springs": "Mountain Lions",
    "University of Connecticut (UConn)": "Huskies",
    "University of Detroit – Mercy": "Titans",
    "University of Hawaii – Manoa": "Rainbow Wahine",
    "University of Illinois – Chicago (UIC)": "Flames",
    "University of Illinois – Springfield": "Prairie Stars",
    "University of Illinois – Urbana-Champaign": "Fighting Illini",
    "University of Louisiana – Lafayette": "Ragin' Cajuns",
    "University of Louisiana – Monroe": "Warhawks",
    "University of Maryland – Baltimore County (UMBC)": "Retrievers",
    "University of Maryland – Eastern Shore": "Hawks",
    "University of Massachusetts – Amherst": "Minutewomen",
    "University of Massachusetts – Boston": "Beacons",
    "University of Massachusetts – Dartmouth": "Corsairs",
    "University of Massachusetts – Lowell": "River Hawks",
    "University of Minnesota – Duluth": "Bulldogs",
    "University of Missouri – Kansas City (UMKC)": "Kangaroos",
    "University of Nebraska – Kearney": "Lopers",
    "University of Nebraska – Lincoln": "Cornhuskers",
    "University of Nebraska – Omaha": "Mavericks",
    "University of Nevada – Las Vegas (UNLV)": "Rebels",
    "University of Nevada – Reno": "Wolf Pack",
    "University of North Carolina – Asheville": "Bulldogs",
    "University of North Carolina – Charlotte": "49ers",
    "University of North Carolina – Chapel Hill": "Tar Heels",
    "University of North Carolina – Greensboro": "Spartans",
    "University of North Carolina – Pembroke": "Braves",
    "University of North Carolina – Wilmington": "Seahawks",
    "University of South Carolina – Upstate": "Spartans",
    "University of Southern Mississippi": "Golden Eagles",
    "University of Tennessee – Chattanooga": "Mocs",
    "University of Tennessee – Martin": "Skyhawks",
    "University of Texas – Arlington": "Mavericks",
    "University of Texas – Austin": "Longhorns",
    "University of Texas – El Paso (UTEP)": "Miners",
    "University of Texas – Rio Grande Valley": "Vaqueros",
    "University of Texas – San Antonio (UTSA)": "Roadrunners",
    "University of the Incarnate Word": "Cardinals",
    "University of Wisconsin – Eau Claire": "Blugolds",
    "University of Wisconsin – Green Bay": "Phoenix",
    "University of Wisconsin – La Crosse": "Eagles",
    "University of Wisconsin – Madison": "Badgers",
    "University of Wisconsin – Milwaukee": "Panthers",
    "University of Wisconsin – Oshkosh": "Titans",
    "University of Wisconsin – Parkside": "Rangers",
    "University of Wisconsin – Platteville": "Pioneers",
    "University of Wisconsin – River Falls": "Falcons",
    "University of Wisconsin – Stevens Point": "Pointers",
    "University of Wisconsin – Stout": "Blue Devils",
    "University of Wisconsin – Superior": "Yellowjackets",
    "University of Wisconsin – Whitewater": "Warhawks",
    "Vermont State University – Castleton": "Spartans",
    "Vermont State University – Johnson": "Badgers",
    "Vermont State University – Lyndon": "Hornets",
    "Warren Wilson College": "Owls",
    "Waynesburg University": "Yellow Jackets",
    "Welch College": "Flames",
    "Westminster College – Missouri": "Blue Jays",
    "Westminster College – Pennsylvania": "Titans",
    "Wheaton College – Illinois": "Thunder",
    "Wheaton College – Massachusetts": "Lyons",
    "William Paterson University of New Jersey": "Pioneers",
    "Wisconsin Lutheran College": "Warriors",
    "Yeshiva University": "Maccabees",
    # D2 alternate names
    "Angelo State University": "Rambelles",
    "Arkansas Tech University": "Golden Suns",
    "Augustana University (SD)": "Vikings",
    "Azusa Pacific University": "Cougars",
    "Biola University": "Eagles",
    "California Baptist University": "Lancers",
    "California State Polytechnic University – Pomona": "Broncos",
    "California State University – Dominguez Hills": "Toros",
    "California State University – East Bay": "Pioneers",
    "California State University – Los Angeles": "Golden Eagles",
    "California State University – Monterey Bay": "Otters",
    "California State University – San Bernardino": "Coyotes",
    "California State University – San Marcos": "Cougars",
    "California State University – Stanislaus": "Warriors",
    "Carson – Newman University": "Eagles",
    "Cedarville University": "Yellow Jackets",
    "Central Washington University": "Wildcats",
    "Christian Brothers University": "Buccaneers",
    "Colorado Christian University": "Cougars",
    "Colorado Mesa University": "Mavericks",
    "Colorado School of Mines": "Orediggers",
    "Colorado State University – Pueblo": "ThunderWolves",
    "Concordia University – St. Paul": "Golden Bears",
    "Dallas Baptist University": "Patriots",
    "Drury University": "Panthers",
    "East Central University": "Tigers",
    "Eastern New Mexico University": "Greyhounds",
    "Embry-Riddle Aeronautical University": "Eagles",
    "Emporia State University": "Hornets",
    "Ferris State University": "Bulldogs",
    "Florida Institute of Technology": "Panthers",
    "Florida Southern College": "Moccasins",
    "Fort Hays State University": "Tigers",
    "Gannon University": "Golden Knights",
    "Grand Valley State University": "Lakers",
    "Harding University": "Lady Bisons",
    "Hawaii Pacific University": "Sharks",
    "Henderson State University": "Reddies",
    "Hillsdale College": "Chargers",
    "Indiana University of Pennsylvania (IUP)": "Crimson Hawks",
    "Lee University": "Flames",
    "Lewis University": "Flyers",
    "Lincoln Memorial University": "Railsplitters",
    "Lindenwood University": "Lions",
    "Lubbock Christian University": "Lady Chaps",
    "Lynn University": "Fighting Knights",
    "McKendree University": "Bearcats",
    "Mercyhurst University": "Lakers",
    "Metropolitan State University of Denver": "Roadrunners",
    "Michigan Technological University": "Huskies",
    "Minnesota State University – Mankato": "Mavericks",
    "Minnesota State University – Moorhead": "Dragons",
    "Minot State University": "Beavers",
    "Missouri Southern State University": "Lions",
    "Missouri Western State University": "Griffons",
    "Montana State University – Billings": "Yellowjackets",
    "Newman University": "Jets",
    "North Greenville University": "Crusaders",
    "Northwest Missouri State University": "Bearcats",
    "Northwest Nazarene University": "Nighthawks",
    "Northern Michigan University": "Wildcats",
    "Northern State University": "Wolves",
    "Nova Southeastern University": "Sharks",
    "Oklahoma Christian University": "Eagles",
    "Palm Beach Atlantic University": "Sailfish",
    "Pittsburg State University": "Gorillas",
    "Point Loma Nazarene University": "Sea Lions",
    "Queens University of Charlotte": "Royals",
    "Regis University": "Rangers",
    "Rollins College": "Tars",
    "Saginaw Valley State University": "Cardinals",
    "Seattle Pacific University": "Falcons",
    "Seton Hill University": "Griffins",
    "Shippensburg University of Pennsylvania": "Raiders",
    "Slippery Rock University of Pennsylvania": "The Rock",
    "Southern Adventist University": "Knights",
    "Southern Arkansas University": "Muleriders",
    "Southern Connecticut State University": "Owls",
    "Southern Indiana": "Screaming Eagles",
    "Southern Nazarene University": "Crimson Storm",
    "Southern New Hampshire University": "Penmen",
    "Southwest Baptist University": "Bearcats",
    "Southwest Minnesota State University": "Mustangs",
    "Southwestern Oklahoma State University": "Bulldogs",
    "St. Cloud State University": "Huskies",
    "St. Edward's University": "Hilltoppers",
    "Tarleton State University": "Texans",
    "Texas A&M International University": "Dustdevils",
    "Texas Woman's University": "Pioneers",
    "Tiffin University": "Dragons",
    "Trevecca Nazarene University": "Trojans",
    "Truman State University": "Bulldogs",
    "Tusculum University": "Pioneers",
    "University of Alabama – Huntsville": "Chargers",
    "University of Bridgeport": "Purple Knights",
    "University of Central Oklahoma": "Bronchos",
    "University of Charleston (WV)": "Golden Eagles",
    "University of Colorado – Colorado Springs": "Mountain Lions",
    "University of Findlay": "Oilers",
    "University of Indianapolis": "Greyhounds",
    "University of Mary": "Marauders",
    "University of Minnesota – Duluth": "Bulldogs",
    "University of Montevallo": "Falcons",
    "University of Nebraska – Kearney": "Lopers",
    "University of New Haven": "Chargers",
    "University of North Georgia": "Nighthawks",
    "University of Sioux Falls": "Cougars",
    "University of Tampa": "Spartans",
    "University of West Alabama": "Tigers",
    "University of West Florida": "Argonauts",
    "University of West Georgia": "Wolves",
    "University of Wisconsin – Parkside": "Rangers",
    "Upper Iowa University": "Peacocks",
    "Valdosta State University": "Blazers",
    "Walsh University": "Cavaliers",
    "Wayne State College": "Wildcats",
    "Wayne State University (MI)": "Warriors",
    "West Chester University of Pennsylvania": "Golden Rams",
    "West Liberty University": "Hilltoppers",
    "West Texas A&M University": "Lady Buffs",
    "West Virginia State University": "Yellow Jackets",
    "Western Oregon University": "Wolves",
    "Western Washington University": "Vikings",
    "Wingate University": "Bulldogs",
    "Winona State University": "Warriors",
    # D3 schools
    "Bethel University (Indiana)": "Pilots",
    "Bethel University (Minnesota)": "Royals",
    "Calvin University": "Knights",
    "Carnegie Mellon University": "Tartans",
    "Case Western Reserve University": "Spartans",
    "Centre College": "Colonels",
    "Claremont-Mudd-Scripps Colleges": "Stags/Athenas",
    "Colorado College": "Tigers",
    "Cornell College (Iowa)": "Rams",
    "Emory University": "Eagles",
    "George Fox University": "Bruins",
    "Gettysburg College": "Bullets",
    "Gustavus Adolphus College": "Gusties",
    "Hamilton College": "Continentals",
    "Hope College": "Flying Dutch",
    "Johns Hopkins University": "Blue Jays",
    "Kenyon College": "Ladies",
    "Luther College": "Norse",
    "Massachusetts Institute of Technology (MIT)": "Engineers",
    "Middlebury College": "Panthers",
    "New York University (NYU)": "Violets",
    "North Park University": "Vikings",
    "Oberlin College": "Yeomen/Yeowomen",
    "Occidental College": "Tigers",
    "Pacific Lutheran University": "Lutes",
    "Pomona – Pitzer Colleges": "Sagehens",
    "Rensselaer Polytechnic Institute (RPI)": "Engineers",
    "Rochester Institute of Technology (RIT)": "Tigers",
    "Rose-Hulman Institute of Technology": "Fightin' Engineers",
    "St. Norbert College": "Green Knights",
    "St. Olaf College": "Oles",
    "Stevens Institute of Technology": "Ducks",
    "Swarthmore College": "Garnet",
    "Tufts University": "Jumbos",
    "University of Chicago": "Maroons",
    "University of Puget Sound": "Loggers",
    "University of Rochester": "Yellowjackets",
    "University of Scranton": "Royals",
    "Wartburg College": "Knights",
    "Washington & Lee University": "Generals",
    "Washington University in St. Louis": "Bears",
    "Wellesley College": "Blue",
    "Wesleyan University": "Cardinals",
    "Whitman College": "Blues",
    "Whitworth University": "Pirates",
    "Williams College": "Ephs",
    "Wittenberg University": "Tigers",
    "Worcester Polytechnic Institute (WPI)": "Engineers",
}


async def enrich_pass2():
    missing = await db.university_knowledge_base.find(
        {"mascot": ""},
        {"_id": 0, "university_name": 1}
    ).to_list(2000)

    updated = 0
    still_missing = []

    for uni in missing:
        name = uni["university_name"]
        mascot = ALT_MASCOTS.get(name)

        # Try fuzzy matching - strip common suffixes
        if not mascot:
            for alt_name, alt_mascot in ALT_MASCOTS.items():
                # Check if the DB name contains the alt name or vice versa
                if alt_name.lower() in name.lower() or name.lower() in alt_name.lower():
                    mascot = alt_mascot
                    break

        if mascot:
            await db.university_knowledge_base.update_one(
                {"university_name": name},
                {"$set": {"mascot": mascot}}
            )
            updated += 1
        else:
            still_missing.append(name)

    print(f"Pass 2: Updated {updated} universities")
    print(f"Still missing mascot: {len(still_missing)}")
    if still_missing:
        for s in still_missing[:30]:
            print(f"  - {s}")
        if len(still_missing) > 30:
            print(f"  ... and {len(still_missing) - 30} more")

    total = await db.university_knowledge_base.count_documents({})
    with_mascot = await db.university_knowledge_base.count_documents({"mascot": {"$ne": ""}})
    print(f"\nMascot coverage: {with_mascot}/{total} ({with_mascot*100//total}%)")


if __name__ == "__main__":
    asyncio.run(enrich_pass2())
