"""Final pass - complete remaining 242 mascots."""
import asyncio, os

with open(os.path.join(os.path.dirname(__file__), '..', '.env')) as f:
    for line in f:
        line = line.strip()
        if '=' in line and not line.startswith('#'):
            k, v = line.split('=', 1)
            os.environ[k] = v.strip('"').strip("'")

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
from database import db

FINAL_MASCOTS = {
    "Tennessee Technological University": "Golden Eagles",
    "University of California – Los Angeles – UCLA": "Bruins",
    "University of Cincinnati": "Bearcats",
    "University of Hawaii at Manoa": "Rainbow Wahine",
    "University of Illinois at Chicago": "Flames",
    "University of North Carolina Asheville": "Bulldogs",
    "University of North Carolina at Chapel Hill": "Tar Heels",
    "University of North Carolina at Charlotte": "49ers",
    "University of Pennsylvania – Penn": "Quakers",
    "University of St. Thomas – Minnesota": "Tommies",
    "Penn State": "Nittany Lions",
    "Southern Illinois University Carbondale": "Salukis",
    "Anderson University – South Carolina": "Trojans",
    "Ashland University": "Eagles",
    "Assumption University": "Greyhounds",
    "Auburn University – Montgomery": "Warhawks",
    "Augusta University": "Jaguars",
    "Augustana University – South Dakota": "Vikings",
    "Barry University": "Buccaneers",
    "Bloomsburg University of Pennsylvania": "Huskies",
    "Bluefield State University": "Big Blues",
    "Cal Poly Humboldt": "Lumberjacks",
    "Caldwell University": "Cougars",
    "California State University – Chico": "Wildcats",
    "California University of Pennsylvania": "Vulcans",
    "Central State University": "Marauders",
    "Chaminade University of Honolulu": "Silverswords",
    "Claflin University": "Panthers",
    "Clarion University of Pennsylvania": "Golden Eagles",
    "Clark Atlanta University": "Panthers",
    "Concord University": "Mountain Lions",
    "Concordia University – Irvine": "Eagles",
    "Concordia University, St. Paul – Minnesota": "Golden Bears",
    "D'Youville University": "Spartans",
    "Davenport University": "Panthers",
    "Davis & Elkins College": "Senators",
    "Dominican University – New York": "Chargers",
    "East Stroudsburg University of Pennsylvania": "Warriors",
    "Edward Waters University": "Tigers",
    "Elizabeth City State University": "Vikings",
    "Emmanuel University – Georgia": "Lions",
    "Georgia College & State University": "Bobcats",
    "Georgian Court University": "Lions",
    "Glenville State University": "Pioneers",
    "Goldey-Beacom College": "Lightning",
    "Holy Family University": "Tigers",
    "King University – Tennessee": "Tornado",
    "Kutztown University of Pennsylvania": "Golden Bears",
    "Lees-McRae College": "Bobcats",
    "Lincoln University Pennsylvania": "Lions",
    "Livingstone College": "Blue Bears",
    "Menlo College": "Oaks",
    "Mercy University": "Mavericks",
    "Miles College": "Golden Bears",
    "Millersville University of Pennsylvania": "Marauders",
    "Missouri University of Science & Technology": "Miners",
    "Northwestern Oklahoma State University": "Rangers",
    "Northwood University – Michigan": "Timberwolves",
    "Paine College": "Lions",
    "Post University": "Eagles",
    "Purdue University – Northwest": "Pride",
    "Quincy University": "Hawks",
    "Roosevelt University": "Lakers",
    "Shaw University": "Bears",
    "Shorter University": "Hawks",
    "South Dakota Mines": "Hardrockers",
    "St. Mary's University – Texas": "Rattlers",
    "The University of Virginia's College at Wise": "Cavaliers",
    "Thomas Jefferson University (Formerly Philadelphia University)": "Rams",
    "University of Arkansas – Fort Smith": "Lions",
    "University of Arkansas at Monticello": "Boll Weevils",
    "University of Hawaii at Hilo": "Vulcans",
    "University of Illinois at Springfield": "Prairie Stars",
    "University of Jamestown": "Jimmies",
    "University of Minnesota – Crookston": "Golden Eagles",
    "University of Missouri – St. Louis": "Tritons",
    "University of Mount Olive": "Trojans",
    "University of North Carolina at Pembroke": "Braves",
    "University of Pittsburgh – Johnstown": "Mountain Cats",
    "University of South Carolina Aiken": "Pacers",
    "University of Texas – Permian Basin": "Falcons",
    "University of Texas – Tyler": "Patriots",
    "Western Colorado University": "Mountaineers",
    "Western New Mexico University": "Mustangs",
    "Westminster College – Utah": "Griffins",
    "William Jessup University": "Warriors",
    "Young Harris College": "Mountain Lions",
    "Anderson University – Indiana": "Ravens",
    "Asbury University": "Eagles",
    "Augsburg University": "Auggies",
    "Augustana College – Illinois": "Vikings",
    "Bard College": "Raptors",
    "Bay Path University": "Wildcats",
    "Belhaven University": "Blazers",
    "Berea College": "Mountaineers",
    "Bethany College – West Virginia": "Bison",
    "Bethel University – Minnesota": "Royals",
    "Blackburn College": "Beavers",
    "Bluffton University": "Beavers",
    "Brevard College": "Tornados",
    "Bryn Athyn College": "Lions",
    "Buena Vista University": "Beavers",
    "Cairn University": "Highlanders",
    "California Institute of Technology": "Beavers",
    "Carlow University": "Celtics",
    "Catholic University of America": "Cardinals",
    "Cedar Crest College": "Falcons",
    "Centenary College of Louisiana": "Ladies",
    "Centenary University – New Jersey": "Cyclones",
    "Clarks Summit University": "Defenders",
    "Colby-Sawyer College": "Chargers",
    "Concordia College – Minnesota": "Cobbers",
    "Concordia University – Chicago": "Cougars",
    "Concordia University – Texas": "Tornados",
    "Dean College": "Bulldogs",
    "Delaware Valley University": "Aggies",
    "Dominican University – Illinois": "Stars",
    "Drew University": "Rangers",
    "Eastern Nazarene College": "Lions",
    "Edgewood College": "Eagles",
    "Elms College": "Blazers",
    "Emmanuel College – Massachusetts": "Saints",
    "Eureka College": "Red Devils",
    "Fairleigh Dickinson University – College at Florham": "Devils",
    "Fitchburg State University": "Falcons",
    "Franciscan University of Steubenville": "Barons",
    "Grace Christian University": "Tigers",
    "Heidelberg University": "Student Princes",
    "Hobart & William Smith College": "Herons",
    "Johnson & Wales University – Charlotte": "Wildcats",
    "Johnson & Wales University – Providence": "Wildcats",
    "Kent State University – Tuscarawas": "Golden Eagles",
    "Keystone College": "Giants",
    "King's College – Pennsylvania": "Monarchs",
    "La Roche University": "Red Hawks",
    "LaGrange College": "Panthers",
    "Lakeland University": "Muskies",
    "Lancaster Bible College": "Chargers",
    "Lasell University": "Lasers",
    "Lesley University": "Lynx",
    "Lyon College": "Scots",
    "Maine Maritime Academy": "Mariners",
    "Maranatha Baptist University": "Sabercats",
    "Marian University – Wisconsin": "Sabres",
    "Marietta College": "Pioneers",
    "Marymount University (VA)": "Saints",
    "Marywood University": "Pacers",
    "Massachusetts College of Liberal Arts": "Trailblazers",
    "Massachusetts Institute of Technology – MIT": "Engineers",
    "Massachusetts Maritime Academy": "Buccaneers",
    "McDaniel College": "Green Terror",
    "Mitchell College": "Mariners",
    "Mount Aloysius College": "Mounties",
    "Mount Mary University": "Blue Angels",
    "Mount Saint Mary College – New York": "Knights",
    "Mount St. Joseph University": "Lions",
    "Nazareth University": "Golden Flyers",
    "Neumann University": "Knights",
    "New England College": "Pilgrims",
    "North Carolina Wesleyan College": "Bishops",
    "North Central University": "Rams",
    "Northland College": "Lumberjacks",
    "Notre Dame of Maryland University": "Gators",
    "Ozark Christian College": "Ambassadors",
    "Penn State Abington": "Nittany Lions",
    "Penn State Altoona": "Nittany Lions",
    "Penn State Berks": "Nittany Lions",
    "Penn State Brandywine": "Nittany Lions",
    "Penn State Erie – The Behrend College": "Nittany Lions",
    "Penn State Harrisburg": "Nittany Lions",
    "Penn State Scranton": "Nittany Lions",
    "Pennsylvania College of Technology": "Wildcats",
    "Pratt Institute": "Cannoneers",
    "Principia College": "Panthers",
    "Ramapo College of New Jersey": "Roadrunners",
    "Regis College": "Pride",
    "Rivier University": "Raiders",
    "Rockford University": "Regents",
    "Roger Williams University": "Hawks",
    "Rosemont College": "Ravens",
    "Russell Sage College": "Gators",
    "Rutgers University – Camden": "Scarlet Raptors",
    "Rutgers University – Newark": "Scarlet Raiders",
    "Saint Elizabeth University": "Eagles",
    "Saint Joseph's College of Maine": "Monks",
    "Saint Mary's College – Indiana": "Belles",
    "Saint Vincent College – Pennsylvania": "Bearcats",
    "Salem College": "Spirits",
    "Salem State University": "Vikings",
    "Sarah Lawrence College": "Gryphons",
    "Sewanee – The University of the South": "Tigers",
    "Shenandoah University": "Hornets",
    "Skidmore College": "Thoroughbreds",
    "Spalding University": "Golden Eagles",
    "St. John Fisher College": "Cardinals",
    "St. Joseph's University – New York": "Bears",
    "St. Mary's College of Maryland": "Seahawks",
    "Stockton University": "Ospreys",
    "SUNY Buffalo State University": "Bengals",
    "SUNY Canton": "Kangaroos",
    "SUNY College at Brockport": "Golden Eagles",
    "SUNY College at Old Westbury": "Panthers",
    "SUNY College at Oneonta": "Red Dragons",
    "SUNY College of Agriculture & Technology at Cobleskill": "Fighting Tigers",
    "SUNY Cortland": "Red Dragons",
    "SUNY Delhi": "Broncos",
    "SUNY Farmingdale State College": "Rams",
    "SUNY Fredonia": "Blue Devils",
    "SUNY Geneseo": "Knights",
    "SUNY Maritime College": "Privateers",
    "SUNY Morrisville": "Mustangs",
    "SUNY New Paltz": "Hawks",
    "SUNY Oswego": "Lakers",
    "SUNY Plattsburgh": "Cardinals",
    "SUNY Polytechnic Institute": "Wildcats",
    "SUNY Potsdam": "Bears",
    "SUNY Purchase College": "Panthers",
    "The College of St. Scholastica": "Saints",
    "The King's College – New York": "Lions",
    "Thiel College": "Tomcats",
    "Thomas College": "Terriers",
    "Trine University": "Thunder",
    "Trinity College – Connecticut": "Bantams",
    "Trinity University – Texas": "Tigers",
    "Trinity Washington University": "Tigers",
    "Union College – New York": "Dutchmen",
    "United States Coast Guard Academy": "Bears",
    "United States Merchant Marine Academy": "Mariners",
    "University of Dubuque": "Spartans",
    "University of La Verne": "Leopards",
    "University of Lynchburg": "Hornets",
    "University of Maine at Presque Isle": "Owls",
    "University of Minnesota – Morris": "Cougars",
    "University of Mount Saint Vincent": "Dolphins",
    "University of Northwestern – St. Paul": "Eagles",
    "University of Olivet": "Comets",
    "University of Pittsburgh – Bradford": "Panthers",
    "University of Pittsburgh – Greensburg": "Bobcats",
    "University of Saint Joseph": "Blue Jays",
    "University of St. Thomas – Texas": "Celts",
    "University of Texas at Dallas": "Comets",
    "University of Valley Forge": "Patriots",
}


async def final_pass():
    updated = 0
    still_missing = []

    for name, mascot in FINAL_MASCOTS.items():
        result = await db.university_knowledge_base.update_one(
            {"university_name": name, "mascot": ""},
            {"$set": {"mascot": mascot}}
        )
        if result.modified_count > 0:
            updated += 1

    # Check remaining
    missing = await db.university_knowledge_base.find({"mascot": ""}, {"_id": 0, "university_name": 1}).to_list(2000)
    total = await db.university_knowledge_base.count_documents({})
    with_mascot = await db.university_knowledge_base.count_documents({"mascot": {"$ne": ""}})

    print(f"Final pass: Updated {updated} universities")
    print(f"Mascot coverage: {with_mascot}/{total} ({with_mascot*100//total}%)")
    if missing:
        print(f"Still missing: {len(missing)}")
        for m in missing:
            print(f"  - {m['university_name']}")


if __name__ == "__main__":
    asyncio.run(final_pass())
